lowThreshold:
  name: "Low Threshold"
  from: 0
  to: 100
  default: 50

ratio:
  name: "Ratio"
  from: 0
  to: 10
  default: 3

kernel_size:
  name: "Kernel Size"
  from: 0
  to: 100
  default: 3

n_bbox:
  name: "Num of Bounding Boxes"
  from: 0
  to: 20
  default: 3